firefighter:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    joint2_to_joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint2_to_joint1
      pid: {p: 500.0, i: 50.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    joint3_to_joint2_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint3_to_joint2
      pid: {p: 3000.0, i: 100.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    joint4_to_joint3_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint4_to_joint3
      pid: {p: 1000.0, i: 25.0, d: 0.0}
    # To add more just add them here as the first one
  
    # Position Controllers ---------------------------------------
    joint5_to_joint4_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint5_to_joint4
      pid: {p: 250.0, i: 10.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    joint6_to_joint5_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint6_to_joint5
      pid: {p: 300.0, i: 25.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    joint6output_to_joint6_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint6output_to_joint6
      pid: {p: 10.0, i: 0.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    gripper_controller_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_controller
      pid: {p: 1.0, i: 0.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    gripper_base_to_gripper_left2_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_base_to_gripper_left2
      pid: {p: 1.0, i: 0.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    gripper_left3_to_gripper_left1_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_left3_to_gripper_left1
      pid: {p: 1.0, i: 0.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    gripper_base_to_gripper_right3_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_base_to_gripper_right3
      pid: {p: 1.0, i: 0.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    gripper_base_to_gripper_right2_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_base_to_gripper_right2
      pid: {p: 1.0, i: 0.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers ---------------------------------------
    gripper_right3_to_gripper_right1_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_right3_to_gripper_right1
      pid: {p: 1.0, i: 0.0, d: 0.0}
    # To add more just add them here as the first one